### ISSUE TITLE
jacksonmapper using single static objectmapper

### ISSUE THREAD

**Issue by maxandersen** [kiota-community/kiota-java-extra#57]
i see a static global objectmapper - that would be problematic in a app with multiple concurrent possible separate context requests. 

any plans on how to fix that and especially how in Quarkus we would get it to use the default available objectmapper managed by quarkus?

**Comment by andreaTP** [comment]
Thanks @maxandersen for taking the time to review the codebase, much appreciated.
I'm working on a fix proposal and will keep you posted on the outcome.

**Comment by andreaTP** [comment]
Closed by #58 now everything flows using Quarkus CDI.

**Comment by maxandersen** [comment]
Awesome!
